load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "mock-external-workload-controller_lib",
    srcs = ["main.go"],
    importpath = "github.com/pingcap/tidb/tests/realtikvtest/scripts/next-gen/mock-external-workload-controller",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_pingcap_kvproto//pkg/externalworkloadpb",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_binary(
    name = "mock-external-workload-controller",
    embed = [":mock-external-workload-controller_lib"],
    visibility = ["//visibility:public"],
)
